#!/usr/bin/env bash

# =====================================================
# Description:
# STEP 10: get data samples file names. The data samples
# are generated by STEP 8(for DUP and DEL) and STEP 9(
# for NEU)
# =====================================================
#
# Created by Yong Bai on 2019/9/18 9:39 AM.

win=1000
# must be 2 precision
ratio=0.10
neu_f=-2.00
dupdel_f=0.01

DATA_SAMPLE_ROOT_DIR="/zfssz2/ST_MCHRI/BIGDATA/PROJECT/NIPT_CNV/f_cnv_out/data"
OUT_FEAT_LIST_FN="${DATA_SAMPLE_ROOT_DIR}/w${win}_r${ratio}_f${dupdel_f}_feat_list.txt"

if [ -f ${OUT_FEAT_LIST_FN} ] ; then
    rm ${OUT_FEAT_LIST_FN}
fi

# DUP/DEL samples
DUPDEL_DATASET_DIR=${DATA_SAMPLE_ROOT_DIR}/w${win}_r${ratio}_f${dupdel_f}/dataset
# NEU samples
NEU_DATASET_DIR=${DATA_SAMPLE_ROOT_DIR}/w${win}_r${ratio}_f${neu_f}/dataset

echo "cd ${DUPDEL_DATASET_DIR} && \
ls -1 -f | sed '1,2d' | awk '{print \"${DUPDEL_DATASET_DIR}/\"\$1}' > ${OUT_FEAT_LIST_FN} && \
cd ${NEU_DATASET_DIR} && \
ls -1 -f | sed '1,2d' | awk '{print \"${NEU_DATASET_DIR}/\"\$1}' >> ${OUT_FEAT_LIST_FN}" > w${win}_r${ratio}_f${dupdel_f}_run10.sh

qsub -cwd -P P18Z10200N0124 -q st_gpu1.q -l vf=8g,p=1 w${win}_r${ratio}_f${dupdel_f}_run10.sh





